"""
Stock Data Explorer - A Streamlit Web Application

This application provides an interactive interface for visualizing stock price data
through dot plots. It uses mock data generation to demonstrate UI functionality
without requiring external API calls.

Author: Generated by Kiro
Date: 2026-01-20
"""

# ============================================================================
# IMPORTS
# ============================================================================

import streamlit as st
import random
from typing import Tuple, List

# ============================================================================
# CONSTANTS
# ============================================================================

# Predefined list of 20 major stock tickers
STOCK_TICKERS = [
    "AAPL", "GOOGL", "MSFT", "AMZN", "TSLA",
    "META", "NVDA", "JPM", "V", "WMT",
    "JNJ", "PG", "MA", "HD", "DIS",
    "BAC", "NFLX", "ADBE", "CRM", "INTC"
]

# ============================================================================
# DATA GENERATION FUNCTIONS
# ============================================================================

@st.cache_data
def generate_mock_stock_data(ticker: str, num_points: int = 30) -> Tuple[List[int], List[float], List[float]]:
    """
    Generate mock stock price data for visualization purposes.
    
    This function creates deterministic mock data based on the ticker symbol,
    ensuring the same ticker always produces the same data. The data simulates
    realistic stock price patterns with daily high and low prices.
    
    Args:
        ticker: Stock ticker symbol (e.g., "AAPL", "GOOGL")
        num_points: Number of data points to generate (default: 30)
    
    Returns:
        Tuple containing:
        - days: List of day numbers [1, 2, 3, ..., num_points]
        - high_prices: List of daily high prices
        - low_prices: List of daily low prices
        
    Invariants:
        - len(days) == len(high_prices) == len(low_prices)
        - high_prices[i] >= low_prices[i] for all i
        - All prices are positive values
    """
    # Use ticker as seed for deterministic random generation
    # Convert ticker string to a numeric seed
    seed = sum(ord(char) for char in ticker)
    random.seed(seed)
    
    # Generate day numbers
    days = list(range(1, num_points + 1))
    
    # Generate base price in realistic range ($50-$500)
    base_price = random.uniform(50, 500)
    
    # Generate price data with realistic volatility
    high_prices = []
    low_prices = []
    current_price = base_price
    
    for _ in range(num_points):
        # Add random walk component (-5% to +5% daily change)
        price_change = current_price * random.uniform(-0.05, 0.05)
        current_price = max(10, current_price + price_change)  # Ensure price stays above $10
        
        # Generate daily high and low around current price
        # High is 0-3% above current price
        daily_high = current_price * random.uniform(1.0, 1.03)
        
        # Low is 0-3% below current price
        daily_low = current_price * random.uniform(0.97, 1.0)
        
        # Ensure high >= low (should always be true by construction, but verify)
        if daily_high < daily_low:
            daily_high, daily_low = daily_low, daily_high
        
        high_prices.append(round(daily_high, 2))
        low_prices.append(round(daily_low, 2))
    
    return days, high_prices, low_prices

# ============================================================================
# VISUALIZATION FUNCTIONS
# ============================================================================

def display_dot_plots(days: List[int], high_prices: List[float], low_prices: List[float]) -> None:
    """
    Display dot plots for high and low stock prices.
    
    Args:
        days: List of day numbers
        high_prices: List of daily high prices
        low_prices: List of daily low prices
    """
    import pandas as pd
    
    # Create DataFrame for high prices
    high_df = pd.DataFrame({
        'Day': days,
        'Price': high_prices
    })
    
    # Display high prices dot plot
    st.subheader("High Prices")
    st.scatter_chart(high_df, x='Day', y='Price', color=None)
    
    # Create DataFrame for low prices
    low_df = pd.DataFrame({
        'Day': days,
        'Price': low_prices
    })
    
    # Display low prices dot plot
    st.subheader("Low Prices")
    st.scatter_chart(low_df, x='Day', y='Price', color=None)

# ============================================================================
# MAIN APPLICATION
# ============================================================================

def main():
    """Main application entry point"""
    # Display application title
    st.title("Stock Data Explorer")
    
    # Stock selector with searchable dropdown
    selected_stock = st.selectbox(
        "Select a stock ticker:",
        options=STOCK_TICKERS,
        index=0  # Default to first ticker (AAPL)
    )
    
    # Display plots only if a stock is selected
    if selected_stock:
        # Generate mock data for the selected stock
        days, high_prices, low_prices = generate_mock_stock_data(selected_stock)
        
        # Display the dot plots
        display_dot_plots(days, high_prices, low_prices)
    else:
        # Display helpful message if no stock is selected (edge case)
        st.info("Please select a stock ticker to view price data.")

if __name__ == "__main__":
    main()
